name: Triggered Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Workflow triggered from Repository B due to PR merge :)"
